nama=input("Nama\t\t\t: ")
nim = input("NIM\t\t\t: ")
ttl = input("Tempat Tanggal Lahir\t: ")
email = input("Email Mahasiswa\t\t: ")
emailu = input("Email Umum\t\t: ")
phone = input("No Hp\t\t\t: ")
alamat = input("Alamat\t\t\t: ")
agama = input("Agama\t\t\t: ")
wn = input("Warga Negara\t\t: ")
sp = input("Status Pekerjaan\t: ")
dosen = input("Dosen Wali\t\t: ")

print("\n\n")
print("\tBIODATA ANDA\t\n")
print("Nama\t\t\t: ", nama)
print("NIM\t\t\t: ", nim)
print("Tempat Tanggal Lahir\t: ", ttl)
print("Email Mahasiswa\t\t: ", email)
print("Email Umum\t\t: ", emailu)
print("No HP\t\t\t: ", phone)
print("Alamat\t\t\t: ", alamat)
print("Agama\t\t\t: ", agama)
print("Warga negara\t\t: ", wn)
print("Status Pekerjaan\t: ", sp)
print("Dosen Wali\t\t: ", dosen)
